test_file: [
  'data/test_sabdab/VL_test.json',
  ]

pdb_root: 'antibody_data/structure_data/sabdab/pdbs/VL/' #'/code/test/struct_pretrain/struct_code/data/debug_pdbs/' #'antibody_data/structure_data/heavy/split_predict/0/'
topk: 20
num_rbf_node: 8
num_rbf_edge: 16

bert_config: 'configs/config_bert.json'
ckpt_path: 'antibody_pretrain/structure_pretrain/struct_code4/output/Pretrain/checkpoint_00.pth'

max_sl: 256
batch_size: 32
bias_layer_num: 12
mlm_probability: 0.1

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.01}
schedular: {sched: cosine, lr: 1e-4, epochs: 25, min_lr: 1e-5, 
            decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 3, cooldown_epochs: 0}

